"""empty message

Revision ID: 92beb86f5da2
Revises: dbc47e148d7a
Create Date: 2021-06-15 21:07:51.496161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92beb86f5da2'
down_revision = 'dbc47e148d7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'1'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'1'"))

    # ### end Alembic commands ###
